server:
  port: 80

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_board
    username: 'root'
    password: '1234'

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true

    jpa:
      hibernate:
        ddl-auto: create #create update none
      show-sql: true
      defer-datasource-initialization: true

    sql:
      init:
        mode: always

---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 162598756069-45u7vj56u5moofdlpjq9gu7e4tnr3flu.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          naver:
            clientId: aSEsViGDtoFUYST7HyrY
            clientSecret: w76LRu9Nrl
            scope:
              - name
              - -email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost/login/oauth2/code/naver

          kakao:
            clientId: e60f35545a7dff10411a90979abc114b
            clientSecret: zPhJhCUavjl8WVkzsdHUo32qrD6AEmYg
            redirectUri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email


        provider:
          naver:
            authorizationUri: http://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response


          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id




